### PR TITLE
Allow damping to equal 0

### PR DESCRIPTION
**Pull request by jamesplease**
The simplest solution to #39. Not backwards compatible but prob. my preferred solution ✌️

### CODE REVIEW

**Comment by skevy** [comment]
Works for me.

**Comment by skevy** [comment]
Closes #39

**Comment by jamesplease** [comment]
✌️thanks a ton @skevy !

**Comment by jamesplease** [comment]
Thanks again for the merge, @skevy . Any chance you've got time to publish a new version with this change to npm? Happy to help in any way if I can.

**Pull request merged**
